apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nvflare.fullname" . }}-efs
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "nvflare.fullname" . }}
  resources:
    requests:
      storage: {{ .Values.efsStorageClass.storageRequest }}
