apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvflare.fullname" . }}
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: flare
      port: {{ .Values.service.flare.port }}
      targetPort: flare
      protocol: TCP
    - name: admin
      port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "nvflare.selectorLabels" . | nindent 4 }}
