apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "nvflare.fullname" . }}
  labels:
    {{- include "nvflare.labels" . | nindent 4 }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efsStorageClass.fileSystemId }}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
